# Generated by Django 3.0.8 on 2020-07-17 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podify_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='podify_app.Podcast'),
        ),
    ]
