# Generated by Django 3.0.8 on 2020-07-20 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podify_app', '0002_episode_podcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='podify_app.Podcast'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='podcast', to='podify_app.Creator'),
        ),
    ]
